import polars as pl
import requests
from pathlib import Path

data = r'''{"name":"playabilities","dateModified":"2023-07-14T00:32:13Z","identifier":1347024,"version":75233389,"url":"https://en.wiktionary.org/wiki/playabilities","html":"playabilities <link href=\"enWiktionary.css\" rel=\"stylesheet\" type=\"text/css\"/> <script src=\"enWiktionary.js\" type=\"text/javascript\"></script> <!DOCTYPE html> <html about=\"https://en.wiktionary.org/wiki/Special:Redirect/revision/75233389\" prefix=\"dc: http://purl.org/dc/terms/ mw: http://mediawiki.org/rdf/\"><body class=\"mw-content-ltr sitedir-ltr ltr mw-body-content parsoid-body mediawiki mw-parser-output\" data-mw-html-version=\"2.8.0\" data-mw-parsoid-version=\"0.21.0.0-alpha20\" dir=\"ltr\" id=\"mwAA\" lang=\"en\"><section data-mw-section-id=\"0\" id=\"mwAQ\"></section><section data-mw-section-id=\"1\" id=\"mwAg\"><h2 id=\"English\">playabilities</h2> <section data-mw-section-id=\"2\" id=\"mwAw\"><h3 id=\"Noun\">Noun</h3> <p id=\"mwBA\"><span about=\"#mwt1\" class=\"headword-line\" data-mw='{\"parts\":[{\"template\":{\"target\":{\"wt\":\"head\",\"href\":\"./Template:head\"},\"params\":{\"1\":{\"wt\":\"en\"},\"2\":{\"wt\":\"noun form\"}},\"i\":0}}]}' id=\"mwBQ\" typeof=\"mw:Transclusion\"><strong class=\"Latn headword\" lang=\"en\">playabilities</strong></span><link about=\"#mwt1\" href=\"./Category:English_non-lemma_forms#PLAYABILITIES\" rel=\"mw:PageProp/Category\"/><link about=\"#mwt1\" href=\"./Category:English_noun_forms#PLAYABILITIES\" rel=\"mw:PageProp/Category\"/><link about=\"#mwt1\" href=\"./Category:English_entries_with_incorrect_language_header#PLAYABILITIES\" rel=\"mw:PageProp/Category\"/><link about=\"#mwt1\" href=\"./Category:Pages_with_entries#PLAYABILITIES\" rel=\"mw:PageProp/Category\"/><link about=\"#mwt1\" href=\"./Category:Pages_with_1_entry#PLAYABILITIES\" id=\"mwBg\" rel=\"mw:PageProp/Category\"/></p> <ol id=\"mwBw\"><li id=\"mwCA\"><span about=\"#mwt2\" class=\"form-of-definition use-with-mention\" data-mw='{\"parts\":[{\"template\":{\"target\":{\"wt\":\"plural of\",\"href\":\"./Template:plural_of\"},\"params\":{\"1\":{\"wt\":\"en\"},\"2\":{\"wt\":\"playability\"}},\"i\":0}}]}' id=\"mwCQ\" typeof=\"mw:Transclusion\"><a href=\"./Appendix:Glossary#plural_number\" rel=\"mw:WikiLink\" title=\"Appendix:Glossary\">plural</a> of <span class=\"form-of-definition-link\"><i class=\"Latn mention\" lang=\"en\"><a href=\"./playability#English\" rel=\"mw:WikiLink\" title=\"playability\">playability</a></i></span></span></li></ol></section></section></body></html> </>\n"}
{"name":"plecopterans","dateModified":"2019-10-16T02:31:43Z","identifier":4926552,"version":55782234,"url":"https://en.wiktionary.org/wiki/plecopterans","html":"plecopterans <link href=\"enWiktionary.css\" rel=\"stylesheet\" type=\"text/css\"/> <script src=\"enWiktionary.js\" type=\"text/javascript\"></script> <!DOCTYPE html> <html about=\"https://en.wiktionary.org/wiki/Special:Redirect/revision/55782234\" prefix=\"dc: http://purl.org/dc/terms/ mw: http://mediawiki.org/rdf/\"><body class=\"mw-content-ltr sitedir-ltr ltr mw-body-content parsoid-body mediawiki mw-parser-output\" data-mw-html-version=\"2.8.0\" data-mw-parsoid-version=\"0.21.0.0-alpha20\" dir=\"ltr\" id=\"mwAA\" lang=\"en\"><section data-mw-section-id=\"0\" id=\"mwAQ\"></section><section data-mw-section-id=\"1\" id=\"mwAg\"><h2 id=\"English\">plecopterans</h2> <section data-mw-section-id=\"2\" id=\"mwAw\"><h3 id=\"Noun\">Noun</h3> <p id=\"mwBA\"><span about=\"#mwt1\" class=\"headword-line\" data-mw='{\"parts\":[{\"template\":{\"target\":{\"wt\":\"head\",\"href\":\"./Template:head\"},\"params\":{\"1\":{\"wt\":\"en\"},\"2\":{\"wt\":\"noun form\"}},\"i\":0}}]}' id=\"mwBQ\" typeof=\"mw:Transclusion\"><strong class=\"Latn headword\" lang=\"en\">plecopterans</strong></span><link about=\"#mwt1\" href=\"./Category:English_non-lemma_forms#PLECOPTERANS\" rel=\"mw:PageProp/Category\"/><link about=\"#mwt1\" href=\"./Category:English_noun_forms#PLECOPTERANS\" rel=\"mw:PageProp/Category\"/><link about=\"#mwt1\" href=\"./Category:English_entries_with_incorrect_language_header#PLECOPTERANS\" rel=\"mw:PageProp/Category\"/><link about=\"#mwt1\" href=\"./Category:Pages_with_entries#PLECOPTERANS\" rel=\"mw:PageProp/Category\"/><link about=\"#mwt1\" href=\"./Category:Pages_with_1_entry#PLECOPTERANS\" id=\"mwBg\" rel=\"mw:PageProp/Category\"/></p> <ol id=\"mwBw\"><li id=\"mwCA\"><span about=\"#mwt2\" class=\"form-of-definition use-with-mention\" data-mw='{\"parts\":[{\"template\":{\"target\":{\"wt\":\"plural of\",\"href\":\"./Template:plural_of\"},\"params\":{\"1\":{\"wt\":\"en\"},\"2\":{\"wt\":\"plecopteran\"}},\"i\":0}}]}' id=\"mwCQ\" typeof=\"mw:Transclusion\"><a href=\"./Appendix:Glossary#plural_number\" rel=\"mw:WikiLink\" title=\"Appendix:Glossary\">plural</a> of <span class=\"form-of-definition-link\"><i class=\"Latn mention\" lang=\"en\"><a href=\"./plecopteran#English\" rel=\"mw:WikiLink\" title=\"plecopteran\">plecopteran</a></i></span></span></li></ol></section></section></body></html> </>\n"}'''

with open("1.ndjson", "w") as f:
  f.writelines(data)
  
# Read with Polars
lf = pl.scan_ndjson("1.ndjson")
lf.select("html").sink_csv("1.csv",
                           include_header=False,
                           maintain_order=True,
                           quote_style="never",
                           line_terminator="\r\n")

with open("1.csv", "rb") as f:
  for row in f:
    print(repr(row[-10:]))
