# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Temporarily modify the rust toolchain version
      run: rustup override set nightly
    - name: Output rust version for educational purposes
      run: rustup --version
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --pre -r requirements.txt
    - name: Run http server
    - uses: actions/checkout@v4
    - run: python -m http.server
    - name: Test hyper-util
    - uses: actions/checkout@v4
      with:
        path: ./hype
    - run: cargo run
