# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:   
    - uses: actions/checkout@v5
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Install DuckDB
      run: |
      curl https://install.duckdb.org | sh
    - name: Yolo
      run: |
        uv run python3 main.py
